"""Initial schema

Revision ID: eb11ac0623d1
Revises: 
Create Date: 2026-03-27 14:02:37.688251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb11ac0623d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_external_id'), 'agents', ['agent_external_id'], unique=True)
    op.create_table('policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('decision_id', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sdk_timestamp', sa.Float(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_agent_id'), 'raw_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_raw_events_decision_id'), 'raw_events', ['decision_id'], unique=False)
    op.create_index(op.f('ix_raw_events_event_type'), 'raw_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_events_processed'), 'raw_events', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_events_session_id'), 'raw_events', ['session_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('session_external_id', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ERROR', 'TIMEOUT', 'HUMAN_HANDOFF', name='sessionstatus'), nullable=False),
    sa.Column('user_context', sa.JSON(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('terminal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_sessions_agent_id'), 'agent_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_external_id'), 'agent_sessions', ['session_external_id'], unique=True)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('parsed_rule', sa.JSON(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('tier', sa.Enum('DETERMINISTIC', 'SEMANTIC', name='policytier'), nullable=False),
    sa.Column('enforcement', sa.Enum('BLOCK', 'WARN', 'LOG_ONLY', 'ALERT_ONLY', name='policyenforcement'), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('decision_nodes',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('decision_external_id', sa.String(length=255), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('parent_decision_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('has_error', sa.Boolean(), nullable=False),
    sa.Column('policy_summary', sa.JSON(), nullable=True),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('action_detail', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('side_effects', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_decision_id'], ['decision_nodes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_nodes_decision_external_id'), 'decision_nodes', ['decision_external_id'], unique=False)
    op.create_index(op.f('ix_decision_nodes_session_id'), 'decision_nodes', ['session_id'], unique=False)
    op.create_table('policy_violations',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('decision_node_id', sa.String(length=36), nullable=True),
    sa.Column('policy_version_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='violationseverity'), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decision_node_id'], ['decision_nodes.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_violations_policy_version_id'), 'policy_violations', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_policy_violations_session_id'), 'policy_violations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_violations_session_id'), table_name='policy_violations')
    op.drop_index(op.f('ix_policy_violations_policy_version_id'), table_name='policy_violations')
    op.drop_table('policy_violations')
    op.drop_index(op.f('ix_decision_nodes_session_id'), table_name='decision_nodes')
    op.drop_index(op.f('ix_decision_nodes_decision_external_id'), table_name='decision_nodes')
    op.drop_table('decision_nodes')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_agent_sessions_session_external_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_agent_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_raw_events_session_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_processed'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_type'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_decision_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_agent_id'), table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('policies')
    op.drop_index(op.f('ix_agents_agent_external_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
